source "https://rubygems.org"

gem "addressable", ">= 2.8.0"
gem "middleman", "~> 4.3.5"
gem "middleman-autoprefixer", ">= 2.10.1"
gem "middleman-blog", ">= 4.0.3"
gem "middleman-livereload", ">= 3.4.6"
gem "middleman-minify-html", ">= 3.4.1"
gem "middleman-syntax", ">= 3.2.0"
gem "middleman-gh-pages"
gem "redcarpet"
gem "pry"
